# Generated by Django 3.2.7 on 2021-10-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_file',
            field=models.ImageField(upload_to='lit_site/static/images', verbose_name='имя картинки'),
        ),
    ]
