# Generated by Django 3.2.7 on 2021-10-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admining', '0002_alter_picture_picture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_text',
            field=models.TextField(default='some text', verbose_name='текст вакансии'),
        ),
    ]
